package com.sample

import java.util.Vector;
import java.util.Iterator;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane; 

import com.sample.HolidaysMain.ChosenBudget;
import com.sample.HolidaysMain.ChosenLengthOfHoliday;
import com.sample.HolidaysMain.ChosenContinents;
import com.sample.HolidaysMain.ChosenCountries;
import com.sample.HolidaysMain.ChosenAge;
import com.sample.HolidaysMain.ChosenDiseases;
import com.sample.HolidaysMain.ChosenSkills;
import com.sample.HolidaysMain.ChosenWillingness;
import com.sample.HolidaysMain.ChosenWayOfSpendingTime;
import com.sample.HolidaysMain.ChosenInterests;
import com.sample.HolidaysMain.Windows;
import com.sample.HolidaysMain.Options;
import com.sample.HolidaysMain.Holiday;
import java.util.List;
import java.util.LinkedList;
//

import com.sample.HolidaysMain.Fact;

/*
rule "Choose diseases"
    when
        w: Windows() and o: Options() and not ChosenDiseases()
    then
		insert (new ChosenDiseases(w.windowCheckbox(o.diseases, "Diseases", "Które z poniższych dolegliwości Ciebie dotyczą?", true)));
end

rule "Choose skills"
    when
        w: Windows() and o: Options() and not ChosenSkills()
    then
		insert (new ChosenSkills(w.windowCheckbox(o.skills, "Skills", "Które z poniższych umiejętności posiadasz?", true)));
end

rule "Choose willingness"
    when
        w: Windows() and o: Options() and c: ChosenSkills() and not ChosenWillingness()
    then
		insert (new ChosenWillingness(w.windowCheckbox(c.generateWillingness(), "Willingness", "Które z poniższych umiejętności chciałbyś posiąść?", true)));
end

rule "Enter bugdet"
	when
		w: Windows() and not ChosenBudget()
	then		
		int budget = w.windowInt("Budget","Podaj proszę maksymalną kwotę, jaką możesz przeznaczyć na wyjazd.",
			"Nie podano dostępnego budżetu.", "Proszę podać liczbę wyrażającą dostępny budżet.", 
			500, "Podano zbyt mały budżet (minimalna wielkość - 500zł).");
		insert(new ChosenBudget(budget));
end

rule "Enter length of stay"
	when
		w: Windows() and not ChosenLengthOfHoliday()
	then
		int days = w.windowInt("Length of stay","Podaj proszę liczbę dni pobytu.",
			"Nie podano długości pobytu (w dniach).", "Proszę podać liczbę wyrażającą długość pobytu (w dniach).", 
			1, "Liczba dni musi być liczbą dodatnią.");
		insert(new ChosenLengthOfHoliday(days));
end

rule "Age"
	when
        w: Windows() and o:Options() and not ChosenAge()
    then
		insert (new ChosenAge(w.windowChooseOne(o.age, "Age", "Proszę wybrać dokładnie 1 z opcji", 2)));
end

rule "Choose way of spending time"
    when
        w: Windows() and o: Options() and not ChosenWayOfSpendingTime()
    then
		insert(new ChosenWayOfSpendingTime(w.windowChooseOne(o.wayOfSpendingTime, "Way of spending time", "Jaki odpoczynek preferujesz?", 0)));
end

rule "Choose interests"
    when
        w: Windows() and o: Options() and not ChosenInterests()
    then
		insert(new ChosenInterests(w.windowCheckbox(o.interests, "Interests", "Czym się interesujesz?", true)));
end
*/


/*
rule "Choose country"
    when
        w: Windows() and o: Options() and c: ChosenContinents() and not ChosenCountries()
    then
    	Vector<String> countries = new Vector<String>();
    	String [] options = new String [5];
    	
		for (int c=0; c<w.getContinent().size(); c++) {
	    	
	    	if (w.getContinent().get(c) == "Afryka") {	    	
			    options[0] = "Algieria";
			    options[1] = "Egipt";
			    options[2] = "Madagaskar";
			    options[3] = "Nigeria";
			    options[4] = "Senegal";
		    }
	    	else if (w.getContinent().get(c) == "Ameryka północna")	{
	    		options[0] = "Jamajka";
			    options[1] = "Kanada";
			    options[2] = "Kuba";
			    options[3] = "Meksyk";
			    options[4] = "Stany Zjednoczone";
			}
		    else if (w.getContinent().get(c) == "Ameryka południowa") {
		    	options[0] = "Argentyna";
			    options[1] = "Brazylia";
			    options[2] = "Chile";
			    options[3] = "Peru";
			    options[4] = "Urugwaj";
			}	    	
		    else if (w.getContinent().get(c) == "Azja") {
		    	options[0] = "Chiny";
			    options[1] = "Filipiny";
			    options[2] = "Indie";
			    options[3] = "Japonia";
			    options[4] = "Rosja";
			}  	
			else if (w.getContinent().get(c) == "Europa") {
		    	options[0] = "Finlandia";
			    options[1] = "Francja";
			    options[2] = "Niemcy";
			    options[3] = "Polska";
			    options[4] = "Włochy";
			} 
		    
		    countries.addAll( w.windowCheckbox(options, "Countries", 
		    	"Których z krajów na kontynencie " + w.getContinent().get(c) + " jeszcze nie widziałeś/widziałaś lub chciałbyś/chciałabyś odwiedzić ponownie?",
		    	false));
		    
		}
		w.changeCuntries(countries);
		update(h);
end

rule "Choose continent"
    when
        w: Windows() and o: Options() and not ChosenContinents()
    then
		insert(new ChosenContinents(w.windowCheckbox(o.continents, "Continents", "Które z kontynetów chciałbyś/chciałabyś odwiedzić?", false)));
end
*/

/* wyznaczanie miejsca na wakacje na podstawie zebranych informacji */ 

rule "Algieria"
	when
		//not Holiday()
		not Fact( name == "Holiday")
		and Fact( name == "ChosenCountries" && values.contains("Algieria")) 
		//and ChosenCountries( getCountries().contains("Algieria") ) 
		and Fact( name == "ChosenAge" && values.get(0) == "dorośli")
		//and ChosenAge( getAge() == "dorośli" )
		and not Fact( name == "ChosenDiseases" && values.contains("Złe znoszenie wysokich temperatur") || values.contains("Strach przed lataniem samolotem"))
		//and not ChosenDiseases( getDiseases().contains("Złe znoszenie wysokich temperatur") || getDiseases().contains("Strach przed lataniem samolotem") )
		and Fact( name == "ChosenInterests" && values.contains("kultura"))
		//and ChosenInterests ( getInterests().contains("kultura") )
		and Fact( name == "ChosenBudget" && values.get(0) > 5000 )
		//and ChosenBudget( getBudget() > 5000 )
		and Fact( name == "ChosenLengthOfHoliday" && values.get(0) >= 10)
		//and ChosenLengthOfHoliday( getLength() >= 10)
	then
		List values = new LinkedList();
		values.add("Algieria");
		insert (new Fact("Holiday", values));
end


